### ISSUE TITLE
No collision

### ISSUE THREAD

**Issue by xeardon** [JoKerr-/LeagueSharp#1]
Hi, in your Ahri assembly isn't included collision, can You add this? Bcs when are minions, and enemy champion for them, this hits minions of all :c

**Comment by JoKerr-** [comment]
I'll look at it when I have some free time, It's a WIP so a lot will change.

**Comment by xeardon** [comment]
I know it's WIP :) Okay, thanks for good script ;)

**Comment by JoKerr-** [comment]
Should be good now, Added other things also.
